# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgQk9CuyepMDkZPMA1GJZ_Djcyr7vKnJ
"""

ligada = True
while ligada:
  num1 = int(input("Digite um numero: "))
  num2 = int(input("Digite outro numero: "))
  operacao = input("Digite a operacao(+, -, *, /): ")
  if operacao == "+":
    print(str(num1) + " + " + str(num2) + " = ")
    print(num1 + num2)
  elif operacao == "-":
    print(str(num1) + " - " + str(num2) + " = ")
    print(num1 - num2)
  elif operacao == "*":
    print(str(num1) + " * " + str(num2) + " = ")
    print(num1 * num2)
  elif operacao == "/":
    print(str(num1) + " / " + str(num2) + " = ")
    print(num1 / num2)
  else:
    print("Operacao invalida")
  nova_conta = input("Deseja realizar outra operação?(s/n)")
  if (nova_conta == "n"):
    ligada = False
    print("Obrigado por usar a calculadora!")
  elif (nova_conta == "s"):
    print("Continuando...")
  else:
    print("Opcao invalida")

